### ISSUE TITLE
dti_fit_csd failing with "AxisError: axis 1 is out of bounds for array of dimension 1"

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-workflows#11]
I am trying to run dti_fit_csd. Right now I am seeing the following error message.

```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/bin/dipy_fit_csd", line 9, in <module>
    run_flow(ReconstCSDFlow())
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/flow_runner.py", line 82, in run_flow
    return flow.run(**args)
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/reconst.py", line 502, in run
    opeaks_indices, ogfa) in io_it:
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/multi_io.py", line 253, in __iter__
    IO = np.concatenate([I, O], axis=1)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
```

I've submitted a new test job to recreate this problem here > https://brainlife.io/project/5b23e74316fe38002748e679/process/5b7c7bbe8042c000445570fd

**Comment by skoudoro** [comment]
Usually, you have this message when it is missing an input parameter or an input parameter is totally wrong. I will check your job

**Comment by skoudoro** [comment]
ok, I just check it, you can not run it like that, the mask is missing.

BTW, I try to start a [new pipeline](https://brainlife.io/project/5b23e74316fe38002748e679/pipeline) but nothing start, is it normal?

**Comment by soichih** [comment]
Ah, OK. I thought the mask was optional for this App. I will make it a required input.

I just checked your pipeline log.

> ..- debug: no matching input DWI

It looks like you are looking for dwi datasets with a tag "hcp" from HCP 3T project. There are no datasets under HCP3T with that tag. Can you try removing it?

**Comment by skoudoro** [comment]
> It looks like you are looking for dwi datasets with a tag "hcp" from HCP 3T project. There are no datasets under HCP3T with that tag. Can you try removing it?

oh ok, done. and it started, perfect. Thanks!

**Comment by soichih** [comment]
I've resubmitted with a mask created by dipy_mask.

I am now seeing the following.

```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:Loading ../5b7c7be08042c000445570fe/5a050a00eec2b300611abff3/dwi.nii.gz
INFO:Computing response function
INFO:Eigenvalues for the frf of the input data are :[0.00129075 0.00029737 0.00029737]
INFO:Ratio for smallest to largest eigen value is 0.230383982928
INFO:CSD computation started.
Traceback (most recent call last):
  File "/usr/local/bin/dipy_fit_csd", line 9, in <module>
    run_flow(ReconstCSDFlow())
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/flow_runner.py", line 82, in run_flow
    return flow.run(**args)
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/reconst.py", line 571, in run
    parallel=False)
  File "/usr/local/lib/python2.7/dist-packages/dipy/direction/peaks.py", line 483, in peaks_from_model
    raise ValueError("Mask is not the same shape as data.")
ValueError: Mask is not the same shape as data.
```

I've checked the dimensions of the mask and dwi inputs

* mask dim           : [  4 107 141 101 106   1   1   1]
* dwi dim             : [  4 107 141 101 106   1   1   1]

I think they are the same shape?

Although.. I thought the mask should be a 3D - not 4D? Maybe I shouldn't be using dipy_mask?

**Comment by skoudoro** [comment]
You can find an example of how it works [here](https://brainlife.io/project/5b23e74316fe38002748e679/process).

I close this issue

**Comment by soichih** [comment]
@skoudoro Thanks for the example. So does this mean dipy CSD / CSA fit Apps will only work with output from Dipy segmentation App? Not just any mask / dwi? Can you comment on what exactly was wrong with the mask that I was using?

**Comment by skoudoro** [comment]
Concerning this issue, Can I send me the mask link you were using @soichi? I need to look deeper why your mask does not work with this app since they are the same size. 

It should work with any mask / dwi, I agree.

**Comment by soichih** [comment]
I just ran it again with mask generated under "Dipy workflows test project". It completed successfully. The mask I used had 3D (dim             : [  3 145 174 145   1   1   1   1]). The one that I ran back in August had 4D, and I believe that was why it was failing. I don't remember how I obtained the mask that had 4D.. however. Is there anyway to add a check so that mask has a proper dimentionality - and display a user friendly error message?

**Comment by skoudoro** [comment]
Great! and really good to know! 

> Is there anyway to add a check so that mask has a proper dimentionality - and display a user friendly error message?

Got it! I will add that

Thanks for this info. I will close this issue when it is done.
