### ISSUE TITLE
dipy_fit_dti workflow failing

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-workflows#7]
@skoudoro I am running following command 

```
> singularity exec -C -e docker://brainlife/dipy:0.14 dipy_fit_dki    --force                 --out_dir /N/dc2/scratch/brlife/carbonate-workflows/5ae9d80750a7120029f0d51a/5ae9d8ca50a7120029f0d51f                 --out_strat what                 ../5ae9d85c50a7120029f0d51b/5941a37f803e87394b473a0f/dwi.nii.gz ../5ae9d85c50a7120029f0d51b/5941a37f803e87394b473a0f/dwi.bvals ../5ae9d85c50a7120029f0d51b/5941a37f803e87394b473a0f/dwi.bvecs ../5ae9d8b750a7120029f0d51d/mask.nii.gz
```

I am seeing the following error message.

```
[0m/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:Computing DKI metrics for ../5ae9d85c50a7120029f0d51b/5941a37f803e87394b473a0f/dwi.nii.gz
INFO:Diffusion kurtosis estimation...
Traceback (most recent call last):
  File "/usr/local/bin/dipy_fit_dki", line 9, in <module>
    run_flow(ReconstDkiFlow())
  File "/usr/local/lib/python3.5/dist-packages/dipy/workflows/flow_runner.py", line 82, in run_flow
    return flow.run(**args)
  File "/usr/local/lib/python3.5/dist-packages/dipy/workflows/reconst.py", line 813, in run
    b0_threshold)
  File "/usr/local/lib/python3.5/dist-packages/dipy/workflows/reconst.py", line 908, in get_fitted_tensor
    dkfit = dkmodel.fit(data, mask)
  File "/usr/local/lib/python3.5/dist-packages/dipy/reconst/dki.py", line 1328, in fit
    raise ValueError("Mask is not the same shape as data.")
ValueError: Mask is not the same shape as data.
```

**Comment by soichih** [comment]
Here is a bit more info..

The wm.nii.gz has following dimension

```
hayashis@xps15:~/Downloads 127 mrinfo wm.nii.gz 
************************************************
Image:               "wm.nii.gz"
************************************************
  Format:            NIfTI-1.1
  Dimensions:        256 x 256 x 256
  Voxel size:        1 x 1 x 1
```

This comes from app-wmMask using freesurfer output (aparc+areg.mgz) convert with RAS - which comes from t1.

On the other hand, dwi has following dimension.

```
hayashis@xps15:~/Downloads $ mrinfo dwi.nii.gz 
************************************************
Image:               "dwi.nii.gz"
************************************************
  Format:            NIfTI-1.1
  Dimensions:        145 x 174 x 145 x 288
  Voxel size:        1.25 x 1.25 x 1.25 x 1
  Dimension labels:  0. left->right (mm)

```

I think we need to preprocess our mask to fit the dwi image?

**Comment by soichih** [comment]
@francopestilli What do you think?

**Comment by francopestilli** [comment]
It looks like the wmmask is in T1w space. We can mrconvert it into DWI space.

**Comment by skoudoro** [comment]
Thank for this info @soichih,  and I confirm that mask need to be preprocessed to fit the dwi image
